[tool]
name = "simulador_ruleta"
version = "0.1.0"
description = "Simulador interactivo de ruleta en Python para evaluar estrategias de apuestas."
authors = ["Tu Nombre <tu.email@ejemplo.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^1.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"